<?php
/**
 * PH2M_PhAddtocart
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Addtocart
 * @copyright  Copyright (c) 2016 PH2M SARL | Bastien Lamamy (bastienlm)
 * @author     PH2M SARL <contact@ph2m.com> | Bastien Lamamy (bastienlm)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /* @var $this PH2M_PhAddToCart_Block_Overlay */ ?>

<div id="ph-addtocart-overlay">
</div>
<div id="ph-addtocart-popup" class="col-sm-5 col-xs-10">
    <div class="summary">
        <div class="added">
        </div>
    </div>
    <ul class="overlay-actions clearfix">
        <li class="btn-overlay" id="close">
            <span><?php echo $this->__('Continue shopping') ?></span>
        </li>
        <li class="btn-overlay" id="go-cart">
            <a href="<?php echo $this->getCartUrl(); ?>">
                <span><?php echo $this->__('See my cart') ?></span>
            </a>
        </li>
    </ul>
</div>
